x-django: &django
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  volumes:
    - ./src:/app
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  backend:
    <<: *django
    command: dev-webserver
    ports:
      - "8000:8000"

  celeryworker:
    <<: *django
    command: celery-worker

  celerybeat:
    <<: *django
    command: celery-beat

  flower:
    <<: *django
    command: celery-flower
    ports:
      - "5555:5555"

  postgres:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
